---
title: "manuscript_v1"
author: "Karthik Thrikkadeeri"
date: "28/11/2021"
bibliography: msc-thesis.bib
output: 
  word_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

## Habitat selection in birds

The origins of the study of habitat selection in birds date back a considerable number of years (see Grinnell, 1917; Hildén, 1965; Svärdson, 1949; Block and Brennan, 1993; Cody, 1985). Its theoretical corpus has evolved from the early correlative models of habitat characteristics and species abundance (MacArthur and Pianka, 1966; Verner et al., 1986; Rosenzweig, 1991), to density dependence (Fretwell and Lucas, 1969; Fretwell, 1972) and more recently to broader multifaceted approaches. Despite the historical ambiguity (Hall et al., 1997) in the terms ‘habitat use’ and ‘habitat selection’, the current understanding is that habitat-use patterns are the end result of habitat-selection processes (Cody, 1985; Block and Brennan, 1993). 

Animals select habitats by assessing the environment at multiple spatial scales and making a series of hierarchical choices (Johnson, 1980; Cody, 1985). Broad-scale selection is reflected in species’ geographic ranges and in the landscape features surrounding home ranges, while fine-scale selection is reflected in microhabitats used for foraging, reproduction, and shelter (Johnson, 1980; Saab, 1999). Species vary in their flexibility of habitat selection, from generalists to specialists, with specialists being less flexible and more susceptible to change (Devictor et al., 2008; Owens and Bennett, 2000). Intraspecific competition forces some individuals to occupy less suitable habitats, widening the ‘habitat breadth’ of that species, while interspecific competition has the opposite effect (Svärdson, 1949). Habitats chosen by animals can influence fitness outcomes via the costs (e.g., predation risk) and benefits (e.g., food availability) of habitat use. 

Notably, the literature on habitat selection in birds, and more generally in free-ranging animals, has a number of biases, the most striking of which is that a majority targets migratory birds (e.g., Gailly et al., 2020; Jenkins et al., 2017; Szymkowiak and Thomson, 2019). This attention is not unjustified---migrants have complex habitat requirements that vary through the annual cycle, across their geographic range, along migratory routes, and at multiple spatial scales. Therefore, investigating their selection patterns may reveal more about the links between organisms and habitat and landscape features than those of resident species would. However, there are additional nested biases: most studies conducted in breeding grounds focus on the pre-breeding and breeding periods (e.g., Danchin et al., 1998; Kleist et al., 2017; Bosco et al., 2021), while some study wintering grounds (usually in the tropics; e.g., Strasser et al., 2019; Ruiz-Sanchez et al., 2017; Albert et al., 2020). To a lesser extent, there are studies concerning stopover sites which are equally important (e.g., Papageorgiou et al., 2017; Wolfe et al., 2014; Alonso et al., 2020; Cohen et al., 2021). There is also a significant body of literature concerning the dynamics of long-distance migrants like shorebirds and other large-bodied birds (e.g., Jourdan et al., 2021; Wang et al., 2019; Devries et al., 2018), which are relatively easier to track at the large scale. 

This disproportionate attention given by researchers to breeding- and nest-site selection could be because the fitness costs and benefits resulting from selection have traditionally been linked with reproductive success and offspring survival. Nevertheless, habitat dynamics during transitional extra-breeding periods can be of great importance as well, given the associated high stress. 

## Post-breeding season

In breeding grounds, habitat selection on the other end of the timeline, i.e., during late summer and early autumn prior to winter migration, remains understudied. Questions regarding community structure and niche breadth take on new dimensions in these periods. For one, territoriality is lower and mobility is higher, allowing birds greater freedom in choosing foraging areas (Uesugi and Murakami, 2007). Moreover, motivations for habitat selection are straightforward and unambiguous; the main challenges are food scarcity coupled with increased food requirements---both for migrants that need to build up enough nutritional reserves and for residents that need to prepare for the oncoming winter (via i.a., food-search and caching)---and the consequently higher predation risk. 

The period of late summer and early autumn, prior to migration, also sees a transition from parent-dependent fledgelings to independent young birds that have to overcome challenges brought by the changing season and by their lack of experience in foraging, navigating and avoiding predators (Anders et al., 1997). Especially to them but also to adults, dense vegetation may provide cover and protection from adverse weather and predators. Furthermore, dispersing juveniles may also collect social information regarding future site quality during the post-breeding period (Betts et al., 2008a). Despite slowly growing evidence that habitat selection in birds may differ seasonally due to the varying ecological requirements during the different seasons (Rivera et al., 1998; King et al., 2006; Akresh et al., 2009; Vitz and Rodewald, 2011; Dittmar et al., 2014), this period remains understudied. 

## The role of competition

In general, interspecific competition is likely to be higher among closely related species due to similar resource use patterns which would lead to smaller overall habitat breadths and overlaps, whereas without competitive effects related species can be expected to overlap more since they have similar basic feeding patterns. Alatalo (1981) found evidence for the prevalence of interspecific competition in the seasonal environment of Finland and noted that this ecological process might be working at two different time scales: either in current ecological time as exemplified by interspecific territoriality in some bird species (e.g., Orians and Willson, 1964) or during the evolution of feeding adaptations of the species—for example, tit species are better adapted to exploit resources in their preferred habitats than in other habitats (Partridge, 1976; Snow, 1954). 

The role of competition as a driver of habitat use can be diverse and can vary with seasons. The competitive release hypothesis (Gauthreaux Jr, 1982; sensu Chapman et al., 2011), concerning specifically intraspecific competition, may just as well be applied to interspecific competition. It states that competition over limited resources in the breeding grounds during winter can predict patterns of partial migration; the decrease in overall resource availability is balanced by a reduction in the number of individuals that need resources. Therefore, species that are highly territorial and competitive in the breeding season might switch to cooperation due to competitive release, as suggested by the widespread occurrence of mixed-species foraging flocks (Greenberg, 2001). In closed habitats such as woodlands, predators attack at a close range and feeding competition is generally lower between species than within, thus favouring mixed associations of small numbers of several to many species (Terborgh, 1990). Risk of predation is thought to be a major factor driving the formation of mixed-species flocks, and species in mixed-species flocks show higher foraging and lower vigilance rates (Sridhar et al., 2009). In the absence of strong competition, birds can be expected to select for habitats that maximise foraging efficiency and, eventually, survival.

## Shifts in foraging strategy

Aside from competition, there are several other factors that may change with the seasons and that birds might select for. Migrating land birds exhibit a high level of foraging and dietary flexibility (Herrera, 1978; Gauthreaux Jr, 1982; Parrish, 1997, 2000; McWilliams and Karasov, 2001; Salewski and Jones, 2006). Species generally considered to be insectivorous, at least during the breeding period, may become facultatively frugivorous in autumn due to lower abundances of arthropods and greater availability and accessibility of fruits (Bairlein and Simons, 1995; Faaborg, 2002; Bairlein, 2003; Ottich and Dierschke, 2003; Newton, 2010; Hernández, 2009). Frugivory, due to the high concentrations of fatty acids in fruits, allows the birds to rapidly build up the fat reserves vital for migration. Within frugivory, birds may exhibit further selectivity by preferentially consuming fruits of native plants over those of invasive ones in late autumn (Smith et al., 2013), even if fruits of the latter are more abundant in this vital pre-migratory period (Gallinat et al., 2020). This is thought to be due to nutritional differences between the two (Ingold and Craycraft, 1983; Smith et al., 2013), although some studies have found no such differences (Greenberg and Walter, 2010) and this preference may also be reversed during winter (Greenberg and Walter, 2010).

It is worth noting an important distinction between temperate forests of the Old and New Worlds. Firstly, there are no specialised obligate frugivorous species in the Old World temperate avifauna. Moreover, European temperate forests have a much lower diversity of fruiting plants than American ones. Among the most widespread fruiting species are bramble *Rubus* spp., bilberry and blueberry *Vaccinium* spp., elderberry *Sambucus nigra*, rowan *Sorbus aucuparia* and alder buckthorn *Frangula alnus*. These species are typical of hedgerows, wood edges and disturbed patches, and old growth mixed forests, but are scarcely found in the large, compact and structurally poor stands of present-day Central European forests. 

Contrarily to the migratory birds reliant on fruits, some wintering birds have been known to consume large numbers of terrestrial arthropods even in winter. Tits (Paridae) in spruce forests commonly consume Lepidoptera, Hemiptera, Coleoptera and spiders (Betts, 1955). For example, Gibb (1960) found that birds in winter consumed around 50% of the stock of the eucosmid Ernarmonia conicolana which is known to be an important food source of blue tits. Other observations from forests suggest that spiders and insects including eggs, larvae, pupae and adults in diapause are also important winter food sources for insectivorous songbirds (Williams and Batzli, 1979; Jansson and Brömssen, 1981; Laurent, 1986). There is also strong evidence that birds can indirectly impact terrestrial plant communities through arthropod predation (Van Bael et al., 2008; Mooney et al., 2010; Mäntylä et al., 2011), although few such studies in temperate regions have explored these effects in winter. 

## Habitat features and quality

Canopy cover, tree density and richness, etc. are commonly used habitat characteristics that are compared with bird abundances or densities. Several studies have shown their links with bird preferences (Vitz and Rodewald, 2007). Modern forestry is a major factor that has been influencing landscape structure (Harris, 1984), and most modern-day forests in Central Europe have been restructured towards commercially exploited plantations dominated by spruce that form compact growths with a closed above-tree layer at maturity (Fanta, 2007). ***But many are highly heterogenous due to management.*** Spatial segregation of habitats at a relatively fine-grained scale is suggested to allow for the co-occurrence of more species. Berg (1997) found that bird abundances correlated positively with the presence of deciduous trees and with tree diameter, while among conifers the Norway spruce *Picea abies* was preferred over the pine *Pinus sylvestris*; total bird densities were also higher in fragments than in forest sites. Furthermore, birds might even show within-season movement up or down gradients of habitat quality. Such questions have scarcely been explored, but there have been affirmative findings at least in the breeding season (Betts et al., 2008b). 

## Aims

In this study, I investigated patterns of habitat selection exhibited by post-breeding forest bird communities. Multiple smaller patches of varying vegetational characteristics were chosen within a single larger stretch of forest, and bird abundances were studied starting from late summer until early autumn, covering the post-breeding season at a fine-grained temporal resolution. The main objectives were to identify the habitat features that are tracked most prominently by forest birds prior to periods of high stress (i.e., autumn-winter), to assess the patterns and magnitude of habitat selection as well as possible temporal dynamism, and to explore the possibilities of ecological interactions and strategies. 


# Methodology

## Study area

The study was conducted over the course of three months (13 weeks), from the first week of July 2020 to the first week of October 2020, in Branišovský les (les: ‘forest’), a typical structurally manipulated and commercially exploited patch of Central European temperate forest situated in České Budějovice, a city in the South Bohemian region (Jihočeský kraj) of the Czech Republic. The forest is located on the western edge of the city between the housing estate Máj and the villages of Branišov, Mokré and Třebín. Together with a southern section called Homolský les, it forms a large forest stretch of around 800 ha segregated from other nearby forests by extensive farmland, large fishponds and settlements (as well as the small airport to the south of Homolský les). Situated at an altitude of approximately 400 m asl, it is technically a mixed forest, but is highly heterogeneous owing to the long history of forestry regimes as well as its connection with rural and military Czech history (having housed, i.a., a military garrison, and functioned as a military shooting range from the times of the Austro-Hungarian empire), and ranges from pure spruce plantations to mixed stands dominated by oak. 

As such, the major tree species include conifers like Norway spruce Picea abies, Scots pine Pinus sylvestris, European larch Larix decidua and silver fir Abies alba, and broad-leaved species such as pedunculate/European oak Quercus robur, sessile/Cornish oak Q. petraea, northern red oak Q. rubra, silver birch Betula pendula, quaking/Eurasian aspen Populus tremula, common/European beech Fagus sylvatica, rowan or European mountain ash Sorbus aucuparia, small-leaved lime or littleleaf linden Tilia cordata, common/European black alder Alnus glutinosa, Norway maple Acer platanoides and sycamore maple A. pseudoplatanus. The commonly found shrub species are alder buckthorn Frangula alnus, rowan Sorbus aucuparia and black/European elderberry Sambucus nigra, while ground layer vegetation is restricted to graminoids like sedges Carex spp. (mostly C. brizoides), bramble Rubus sp. and European blueberry Vaccinium myrtillus.

## Study design

The entire forest stretch—with the exception of parts of Homolský les in the south, some of which were either too disturbed or had restricted access (being near the airport)—was effectively covered by selecting 32 evenly distributed circular sampling points of 30 m radius (Figure 1). The total forest area under consideration was thus around 400 ha, while the absolute cumulative area covered by my sampling points was approximately 9 ha, as they were chosen such that each point was at least 250 m away from its neighbours (although this boundary was lowered to 200 m in three cases). Clear cuts were avoided as much as possible. Therefore, the selection of sampling points was not done at random. 
 
Figure 1: Map showing 32 sampling points evenly distributed over the study area: Branišovský les, Czech Republic.

Before the beginning of the main study, each point was visited and preparations were made. GPS coordinates were recorded from the centre of each point using the GPS Essentials Android application and saved for reference. The centre of a point was signified using red-and-white tape tied and/or stuck to the trunk or branch of a tree, which ensured identifiability and hence constancy. A radius of 20 m from the centre was also denoted using tape stuck/tied to trees in two opposite directions. In addition, three equidistant sub-points within 10–15 m of the centre were chosen to sample canopy cover from. 

To measure canopy cover, first, photographs of the canopy were taken from each of the three sub-points (named A, B and C) using a Nikon D3200 camera with a standard 18–55 mm kit lens set to the 18 mm focal length. Measurements were always taken by the same observer (myself) from the same locations (sub-points identified by the tapes) and at the same height (around 1.9 m above the ground; assured by holding the camera horizontally tethered to my neck by the strap, and positioning both the camera and my person vertically upright and/or perpendicular to the ground, whichever appropriate to the topography). The photographs were then analysed using ImageJ software (Rasband, 1997) by converting to binary black-and-white images (see Forester, 2011) and calculating the percentage of cover across the whole image (see Figure S1). The measurements from A, B and C sub-points were averaged to represent mean canopy cover of a point, while the standard deviation of the three values represented the heterogeneity in canopy cover in the point (high values signifying high heterogeneity). 

Aside from canopy cover, other vegetation characteristics were also recorded initially. The tree, shrub and herb species were identified, and the vertical strata to which they belonged were noted. Some species like S. aucuparia are highly variable and commonly occur as both shrubs and trees. Since my primary question concerned the structural characteristics of vegetation rather than their taxonomic or biological traits, vertical stratification was given precedence over the tree-shrub-herb classification, and the various plants in each of my sampling points were categorised as follows. Plants of height ≤ 1 m above the ground belonged to the ‘Herb’ layer (this therefore included both woody- [like Rubus] and non-woody stemmed [like graminoids] plants, and did not exclude graminoid leaves that extended beyond 1 m from the ground); plants 1–4 m in height belonged to the ‘Understorey’ (this therefore included shrubs like S. aucuparia and F. alnus as well as young individuals of trees like P. abies); and plants ≥ 4 m in height belonged to the ‘Canopy’ (this therefore occasionally included S. aucuparia). 

The species information was used to calculate plant species richness and diversity in each of the points. Shannon’s diversity index (Shannon, 1948) was used because it emphasises the richness component of diversity, and is more sensitive to rare types and less to dominant ones, and is therefore generally recommended for ecological questions like the ones in this present study (see Nagendra, 2002). The number of ‘Canopy’ and ‘Understorey’ plants within the 20 m radius was counted and used to calculate density per 100 m2. Counts were not taken for the ‘Herb’ layer due to the difficulty in some cases in determining what constitutes a single stem. Moreover, it is unlikely that birds track ground layer vegetation at the level of individual stems, and so this was not pertinent to my primary question. Instead, the species that covered >50% of the ground was considered to be the ‘Dominant Ground Vegetation’ (in some cases, this was moss) and this was used in analyses. In addition, presence or absence of moss in the point was noted separately regardless of whether or not it was the dominant ground layer vegetation, as its presence usually indicates the quality of and disturbance within the forest patch (see e.g., Berdugo et al., 2018; Cornelissen et al., 2007). 

The proportion of ‘Canopy’ trees that are deciduous was calculated as this has been shown to be more important than measures of tree diversity (Berg, 1997). Finally, the habitat class of each of the 32 points was recorded as ‘Interior’, ‘Road’ or ‘Edge’ according to whether or not asphalt roads and forest-to-farmland transitions occurred within 150 m from the centre of the point. This was done using an aerial map (Mapy.cz) in which asphalt roads, farmlands and forests are all clearly visible and distinguishable.

Care was taken to ensure that the selected set of points represented sufficiently well the natural range and diversity of habitat characteristics in the forest (see Figure S2 for some comparisons). This was confirmed by an NMDS plot of the sampling points with their measured characteristics; there was no major clumping of points and no observable residual pattern in the ordination, suggesting that the points and their features were sufficiently diverse. Linear correlations of the measured habitat variables were tested using Pearson’s product moment correlation before building the statistical models, so as to spot and exclude some of the correlated variables and thereby avoid multicollinearity. For instance, the mean canopy cover was found to correlate significantly with tree density and with canopy heterogeneity, but tree density and canopy heterogeneity in turn were not correlated (Figure S6). 

I recorded canopy cover for all my sampling points every week throughout my study period, as I had originally expected to capture a decline in cover due to autumn senescence. However, most of the deciduous trees in my points still bore leaves even during my last sampling (in the first week of October) and the weekly measurements did not show any discernible negative trend. At the same time, there was variation in each of the unique values (A, B and C) around a mean, likely due to varied weather conditions in each of the samplings affecting the positions of leaves (e.g., winds) and lighting. Hence, I decided to average the 13 weekly measurements of both mean canopy cover and canopy heterogeneity for each sampling point to provide more accurate measures of both. Furthermore, along with the bird counts and canopy cover measurements, phenological characteristics of leaves, flowers and fruits of the plants in each point were also recorded weekly on an ordinal scale in order to track fruiting, flowering and leaf senescence patterns along the season. The presence of intense shrub herbivory in some cases was recorded. The demarcating tapes were monitored and replaced if required. 

## Bird counts

To answer the primary question regarding habitat selection patterns of post-breeding forest birds, I used point counts to observe birds at each of the 32 sampling points every week for 13 weeks (8 July 2020–1 October 2020). Each point being located at least 250 m from its neighbours assured spatiotemporal independence of consecutive point counts. Sampling was done on 2–3 days in the middle of the week while the remaining days served to delineate and separate two successive ‘temporal units’. This enabled meaningful comparisons of bird abundances across weeks, as each would be sufficiently independent of the other and would thus represent a distinct time point (Table 1). 

To ensure logistical feasibility of the sampling design, bird counts were conducted by two observers, myself and Inga Freiberga. The binoculars used were Nikon Aculon A211 8x42 and Nikon Prostaff 7s 8x42 respectively. Inga has a Master’s degree in Ornithology and years of active experience with birdwatching and mist-netting across Europe. I had spent 170+ hours in the field birdwatching by the start of the study and additionally, bird songs and calls were regularly reviewed using online repositories such as Macaulay Library and xeno-canto, in order to familiarise myself with the seasonally changing vocalisations and thus ensure best possible bird detection. 

We, myself and Inga, each conducted 6–10 bird counts per sampling day, during the first five hours after sunrise (which shifted forward by around 10 minutes every week). Overcast and rainy days were avoided. The subset of points that each observer sampled was alternated every week, and the order in which the points were sampled was reversed as well. The counts were conducted with the observer standing in the centre of the point, and each count was of 20 minutes, chosen after a few recce counts as the optimal count duration for this study period. Count-specific information like observer name, date, week, weather (overcast, cloudy, partially cloudy or clear sky), wind (strong winds, light winds or no winds) and visibility (misty or clear), and start and end times were noted in each count. The 20-minute duration was divided into four intervals of five minutes each. All birds heard or seen were recorded, along with complementary information associated with each detection such as the time interval (one of the four 5-minute units), distance class (see next), type of detection (visual or auditory or both) and behaviour such as flyover (over the forest, within the forest canopy or not flying) and foraging (yes or no). If foraging, the plant species on which the bird was found foraging was noted as well as whether or not it was feeding on fruits. 

Table 1: The continuous measure of time (Week) used to test for patterns in habitat selection, with corresponding weeks (starting on Monday) in the Gregorian calendar.

Week	Corresponding Gregorian week
1	6 July 2020–12 July 2020
2	13 July 2020–19 July 2020
3	20 July 2020–26 July 2020
4	27 July 2020–2 August 2020
5	3 August 2020–9 August 2020
6	10 August 2020–16 August 2020
7	17 August 2020–23 August 2020
8	24 August 2020–30 August 2020
9	31 August 2020–6 September 2020
10	7 September 2020–13 September 2020
11	14 September 2020–20 September 2020
12	21 September 2020–27 September 2020
13	28 September 2020–4 October 2020

Distance classes referred to five radial bins from the centre of the point: 0–10 m, 10–20 m, 20–30 m, 30–50 m and >50 m. This was done in case detection probabilities needed to be calculated, so additionally, birds were observed for whether or not they entered the 30 m radius (i.e., entered the point) at any time during the count, as this would signify the bird’s ‘use’ of the habitat. The distance sampling approach using detection probabilities was not appropriate for the study due mainly to insufficient detections. Moreover, estimating true population sizes of birds was not an objective of the study, and hence raw abundances from the point counts were still suitable. Since a large majority of the detections were auditory, errors in detection were ascribed more to differences in bird vocalisation behaviour with the progressing season than to differences in vegetation characteristics of sampling points. Hence, since analyses were done at the scale of weeks, inferences are not expected to be highly unreasonable.

Distances beyond 20 m from the centre, particularly the third class of 20–30 m, were estimated with the help of the red-and-white marking tapes as references—the observer would mentally note the distance from the centre of the point to one of the tapes demarcating the point boundary, halve it, and then transplant this half to the other side of the tape so as to estimate the 30 m mark. The accuracy of such distance estimation obviously decreases with increasing distance, hence the distance bins beyond 30 m were wider. All birds were identified to species level when possible, but some closely related cryptics such as Phylloscopus spp., Certhia spp., Regulus spp. and Dendrocopos spp. are easy to confuse and difficult to identify correctly with just the occasional post-breeding vocalisations, and hence were often recorded as ‘spuhs’. Only those birds that entered the 30 m radius during point counts and were not flying over the forest have been considered for analysis in the present study. 

Prior to analysis, bird species were classified based on feeding guild as well as migration strategy. Feeding guild was determined using data from an extensive network of European ornithologists (Gregory et al., 2007, pt. Appendix 1) complemented with species descriptions from Birds of the World (Billerman et al., 2020). Migration strategy was assigned following Czech ornithological data; species of which >75% of the Czech breeding population migrates either short or long distances (categories 3 and 4 in Cepák et al., 2008) were considered as complete migrants for the purposes of this study; those species which have ‘regular and abundant wintertime occurrence in the Czech Republic’ were considered partial migrants (category 2 in Cepák et al., 2008; see also Št’astnỳ and Hudec, 2011); and the residents of category 1 (Cepák et al., 2008) were considered true residents. 

## Predation

Survey of predation pressure was conducted at the same 31 points as the ornithological surveys (one point excluded due to the absence of suitable foliage). Siddharth Khopkar assisted with this experimental part, while Kateřina Sam confirmed the accuracy of bite identifications. We used dummy caterpillars exposed on the trees and shrubs to monitor attacks by natural enemies. Caterpillars were made from natural-looking, dark green-coloured modelling clay (Koh-i-Noor Hardtmuth, České Budějovice, Czech Republic), which is malleable, oil-based and non-toxic. We modelled artificial caterpillars by pressing the plasticine through a stainless-steel clay extruder gun (Antoble) to ensure that each caterpillar had an absolutely smooth surface. Artificial caterpillars were 20 mm long and 3 mm in diameter. The artificial caterpillars resembled generic non-conspicuous lepidopteran larvae commonly found on oaks in Central Europe (e.g., autumnal moth Epirrita autumnata, winter moth Operophtera brumata). This method has been successfully used in previous studies (e.g., Howe et al., 2009; Drozdova et al., 2013; Mrazova and Sam, 2018; Sam et al., 2015). 

The survey started with a one-month delay respective to the ornithological part of the study, and each sampling usually took two days to finish. Thus, the survey spanned from Week 5 to Week 12 of the main study. During experimental days 1 and 2 (27th and 28th of July 2020), we exposed caterpillars on shrubs and trees and other foliage, within the 30 m radius of the centre of the point, at heights between 1 and 2.5 m above the ground. We pinned the 20 dummy caterpillars on bases of leaf stalks, at a minimal distance of 1 m from each other. 

A week later, we visited all the points again, checked for missing and damaged dummy caterpillars, and collected them for further reference. Caterpillars without visible damage were left unchanged. Damaged ones were replaced by new ones, placed within a 50 cm radius but not on the same leaf. An artificial caterpillar was considered as damaged by insectivorous birds if it had some unequivocal attack marks distinctive to birds (Low et al., 2014). Caterpillars attacked by arthropods only were considered to be attack-free. Some dummy caterpillars were missing, and as we were not able to identify their fates and times of disappearance, they were excluded from the dataset prior to calculations of the predation rate in proportions (i.e., missing caterpillars were considered as having never been exposed). At any given time, there was a total of 620 artificial caterpillars exposed to predators. Given that dummy caterpillars were exposed eight times by the end of the study period, with a total exposition time of 66 days, this yielded 4,960 potential predation events and 40,920 caterpillar exposition days respectively. 

## Analysis

The bird data containing all observations from the point counts was filtered to exclude the birds that did not enter the 30 m radius during the count, those that flew over the forest canopy and those that were not identified to genus level. To assess patterns of habitat selection by birds, analyses were conducted at three main levels of response, using generalised linear mixed models (GLMM). Mixed models were used to account for the repeated samplings, attributing a random variability to them so as to avoid pseudoreplication. Bird abundance at various levels was used as the response variable. The measured habitat variables without the ones excluded due to correlations represented the pool of candidate predictors. This set of plausible predictors was then used to build models using an information-theoretic approach (Burnham and Anderson, 1998), viz., the Akaike Information Criterion (Akaike, 1973, 1974). More specifically, the corrected AIC (AICC) was used (Hurvich and Tsai, 1989). Traditional parametric tests and p-values were avoided as they are not reliable for complex models such as GLMMs. Non-focal variables were tested for effects first, after which the focal habitat characteristics were tested. 

To assess differences in bird predation rates across the study area and with time, analysis was done using GLMMs with the habitat variables as predictors. Additionally, correlation between bird predation rates and bird abundances were checked using Pearson’s product moment correlation. All analyses were done using R version 4.0.2 (R Core Team, 2020). Individual figures with multiple graphs were composed using the patchwork package for R (Pedersen, 2020).

## Regressions of bird abundances with habitat variables

First, I investigated whether there were any patterns of habitat selection at the highest level of all bird species by summing all the individual species abundances per point count to obtain one abundance value for each count. This ‘bird abundance’ was then used as the response variable in the models. GLMMs were constructed using the lme4 package (Bates et al., 2015), starting with a null model and building up from it. The null model included observer as a fixed effect and sampling points and days as crossed random effects. The residuals were modelled as coming from a Poisson distribution with a log link function. There was a prominent observer effect, with me making more detections on average than Inga (see Figure S4). Point ID was used a random effect because of repeated sampling in the same points over the 13 weeks, and sampling day was used as a random effect to account for the random variability in each unique day. 

Next, the week variable, which clearly had a strong effect (abundances were higher towards the end of the study period; noticed even during the bird counts), followed by other non-focal (‘nuisance’) variables such as weather, visibility and time of count (on an ordinal scale from 1 to 10 representing which part of the first five hours of sunrise the count was done in) were added to the null models and comparisons were made of AICC values of all the models using the AICctab() function from the bbmle package (Bolker et al., 2020). If the addition of a variable did not result in a substantial decrease of AICC respective to the number of degrees of freedom it used (following the rule of thumb of 2 dAICC per df), it was discarded, and otherwise it was retained in the model. Such a stepwise procedure was repeated until the final model was obtained. However, the null model in the beginning was not compared with a simpler model, as the variables were all assumed to have an effect and discarding them would only be statistically incorrect. 

None of the non-focal variables ended up in the model, and finally other focal variables were tested including habitat class, presence of moss, log-transformed variables of canopy heterogeneity and tree density and square root-transformed understorey density (transformations done to prevent outliers from gaining too much leverage), scaled proportion of deciduous trees, tree species diversity and richness, and dominant herb. Understorey richness and diversity were not tested because the sampling points did not have sufficient diversity in understorey species and moreover, it was unlikely that birds would track, for instance, spruce saplings (which indeed belonged to my ‘Understorey’ classification). Instead, understorey density was thought to be a meaningful and more important predictor. For continuous or ordinal variables, both linear and polynomial terms were tested since there was no reason to assume a linear relationship with the predictors. If a variable was found to be important, its interaction with ‘Week’ was next tested, this being one of the primary questions of my study (i.e., whether or not certain habitat selection criteria changed with the progress of the season).

Model diagnostics of all models were explored using the DHARMa package (Hartig, 2020) for distributional assumptions, heteroscedasticity, over-/underdispersion and zero-inflation. Since the model with the default optimiser was facing convergence problems, the BOBYQA optimiser was used which resolved the issue. Once the selection was complete, parsimony was further tested by dropping some complex interaction terms. Finally, the most parsimonious model was obtained. 

The next level of response investigated was the guild level. The original bird observations were summarised by guild so as to obtain for each point abundance values of all the guilds that were observed. Models were then built separately for the two guilds that had the highest number of overall detections, insectivores (rather, invertebrate-feeders) and omnivores. Using the lme4 package resulted in several errors and warnings regarding convergence and singular fits, but the same model specifications using the glmmTMB package (Brooks et al., 2017) did not, and hence the latter was used in further steps. The data summarised at guild level was insufficient for the proper utilisation of two crossed random effects (as was done in the first model), so the random effect of day, which had less estimated variance than that of the point, was excluded from the models. This did not result in major differences in the fixed effects estimates so was not considered to be an issue. Model building and checking of model diagnostics was done in the same way as in the first case. 

To explore whether patterns differed between migrant and non-migrant species, the bird data was summarised by migration strategy and attempts were made to build GLMMs using the glmmTMB package. However, while a good fitting model was obtained for non-migrants (which had the highest number of overall detections), data for the other two categories seemed to be unsuitable and insufficient. The data showed significant one-inflation when tested (using functions in the DHARMa package) relative to both Poisson and negative binomial distributions, i.e., the number of ‘1’ count observations was too high for a standard Poisson or a standard negative binomial. This one-inflation in turn also caused underdispersion, which was removed neither on switching to distributions suited to underdispersed data (such as the Generalised Poisson and Conway-Maxwell Poisson), nor on introducing a zero-inflation term. The same problem occurred during attempts to build models at the species-level, i.e., looking at patterns of habitat selection for certain selected species (incidentally, the ones with most overall detections). The results of these questions were expected to be interesting, but as the data didn’t seem much suited to a binomial distribution either, I accepted that better data would be required and thus this approach was abandoned. Finally, separate models were built to test whether bird abundances were linked to the phenology of the fruiting plants Rubus sp., Vaccinium sp., F. alnus and S. aucuparia but there was no detectable relationship. 

## Ordinations of selected bird species communities

In order to gain a qualitative idea of habitat selection at the species level, communities defined by the preselected species—four invertebrate-feeders (European robin Erithacus rubecula, treecreepers Certhia spp., common chiffchaff/willow warbler Phylloscopus spp., and goldcrest/common firecrest Regulus spp.) and four omnivores (European great tit Parus major, Eurasian blue tit Cyanistes caeruleus, Eurasian nuthatch Sitta europaea, and great-/middle spotted woodpeckers Dendrocopos spp.)—across the entire study area were compared between the start and the end of the study period. Data from the first three weeks of the study (1–3) were aggregated to represent the ‘post-breeding period’ (PB) and data from the last three (11–13) were aggregated to represent the ‘pre-migratory period’ (PM). Abundances in the same points in different weeks were summed. Principal Component Analyses (PCAs) scaled by species were done using the vegan package (Oksanen et al., 2020) and the ordinations were plotted using the first two principal components. The measured habitat variables were fitted to the ordination diagrams using the envfit() function from vegan, and the two plots were then compared to see similarities and differences in the bird species between the two periods and how occurrences of these species over the study area were generally structured. 

## Bird predation across the points and over time

First, the variation in bird predation rates across the sampling points and over the course of the 13 weeks of the study was explored using a generalised linear model (GLM) with binomial error distribution. A binomial response variable of total bird predations (number of caterpillars attacked by birds) over total non-predations was modelled against fixed effects of point and week. This model was updated to use a second-order polynomial of the week, which provided an even better fit (11 dAICC on 1 df). 

However, since it was now ascertained that the points were indeed different in terms of bird predation, it was decided to replace the point variable with habitat variables to create a more parsimonious as well as informative model, while accounting for random variation by using point as a random effect. Variables from the same pool as before were tested—expecting plant diversity to be an important predictor of predation rates (e.g., Leles et al., 2017)—in generalised linear mixed models with binomial error distribution using the lme4 package. Finally, Pearson’s product moment correlation between bird abundances and the predation rates in each point in each week was calculated.

# Results

In total, over the course of 13 weeks and across all points, 7,367 bird detections of 69 species were made, but 62% of the detections were of birds that did not enter the 30 m radius, or were flyovers above the forest canopy or were unidentified to genus level. Hence, the data considered and analysed in the present study comprised 2,840 detections of 45 species. The average number of birds detected per point count varied from 5 in Week 1 to 9 in Week 13 (Figure 2). Of the 2,840 detections, 78% (2,209) were purely auditory, 7% (201) were purely visual and 15% (430) were both, and this did not change majorly with weeks or across points (Figure S3).

There were 494 records of birds foraging, although just 2 of them were of birds feeding on fruits. Even in the full unrestricted dataset, there are records of just 14 birds feeding on fruits, and half of these birds were from a single observation. The fruiting plant species most birds fed on was rowan S. aucuparia although one record was of a blackbird Turdus merula feeding on Rubus sp. Most of the birds feeding on fruits were thrushes, but one instance was of a Eurasian blackcap Sylvia atricapilla and another of two Eurasian jays Garrulus glandiarus. Although this data is very limited and cannot be used in further analyses, the tiny proportion of overall foraging observations that were of frugivory is certainly an interesting point.

In the full dataset, I observed 54.24% of the total detections (3,996/7,367) and Inga observed 45.76% (3,371/7,367), while in the restricted data analysed in this study, I observed 70.63% (2,006/2,840) and Inga observed 29.37% (834/2,840) (Figure S4 and Figure S5). Clearly, the overall detection rates are not considerably different between the observers but the discrepancy in the restricted dataset was most likely caused due to errors in distance estimation in the field and became evident on filtering the data (i.e., excluding the birds that did not come within 30 m of the centre). Specifically, either I underestimated the distances at which detections were made (thereby including more birds as having come within 30 m) or Inga overestimated them (thereby including less birds as having come within 30 m), or both. This contributes majorly to the observer effect in the later models. Nevertheless, only the restricted data is considered hereinafter.
 
Figure 2: The trends in bird detections per point count with season and habitat. (A) Large circular dots represent mean bird detections per point count for each week averaged over all sampling points. Whiskers represent 95% confidence intervals (CIs). (B) Thick horizontal bars within boxes represent median value of bird detections per point count for each point over all sampling weeks. Top and bottom box hinges are the 1st and 3rd quartiles respectively (25th and 75th percentiles). Respective whisker ends are distances to data points ≤ 1.5 × IQR (interquartile range) from respective hinges. Small circular dots are data points ≥ 1.5 × IQR from hinges (outliers).

## Habitat selection in forest birds

The final model was a GLMM with Poisson error distribution (and log link) fitted with the BOBYQA optimiser (see Table 2 for the model selection steps). It contained the all-species abundance as the response and crossed random effects of sampling point and day. The predictors selected as important were observer, week, canopy heterogeneity, tree density, dominant ground vegetation and its interaction with week. 

Table 2: GLMMs using abundance of all birds as the response. Models at each step of term addition/deletion are shown (as ‘all.x’) with their corresponding information such as degrees of freedom (df), predictor terms, log-likelihood, AICC (which was used as a selection criterion) and Akaike weight. ‘CH’: canopy heterogeneity; ‘TD’: tree density; ‘DOM’: dominant ground vegetation.

Model	df	Predictors	logLik	AICc	Weight
all.6	15	log(CH) + log(TD) + DOM + week:(DOM) + observer + (1|point) + (1|day) + week 	-1,029.278	2,089.804	0.626
all.5	17	log(CH) + log(TD) + DOM + week:(DOM) + week:log(CH) + week:log(TD) + observer + (1|point) + (1|day) + week 	-1,028.312	2,092.223	0.187
all.4	17	log(CH) + log(TD) + DOM + week:(DOM) + week:log(CH) + week:log(TD) + observer + (1|point) + (1|day) + week 	-1,028.312	2,092.223	0.187
all.3	9	log(CH) + log(TD) + week:log(CH) + week:log(TD) + observer + (1|point) + (1|day) + week 	-1,042.747	2,103.953	0.001
all.2	7	log(CH) + log(TD) + observer + (1|point) + (1|day) + week 	-1,046.654	2,107.594	0.0001
all.1	5	observer + (1|point) + (1|day) + week	-1,049.992	2,110.136	0.00002

Selected model, ‘all.6’:
bird abundance ~ observer + (1|point) + (1|day) + week + log(canopy heterogeneity) + log(tree density) + ground vegetation + week:(ground vegetation)

There was an overall increase in bird abundance towards the end of the study period. Otherwise, abundance showed positive and negative trends with log-transformed variables of canopy heterogeneity and tree density respectively (Figure 3). These trends did not change detectably over the course of the study period. 

Here, it is worth noting that in the process of selection of candidate habitat variables, canopy heterogeneity correlated negatively with canopy cover at a significant level (r = -0.533, p = 0.0017). However, the relation was stronger at high values of canopy cover and weaker at low values, which is a direct physical result—with higher average cover, the potential variability in cover is lower. Additionally, tree density correlated significantly with canopy cover, albeit in the opposite direction (r = 0.526, p = 0.002). In spite of these two correlations, heterogeneity and tree density remained uncorrelated (r = -0.246, p = 0.1745). Further, tree density also correlated negatively with proportion of deciduous trees at a significant level (r = -0.545, p = 0.0013), but seemed to be the more important predictor in the models.

The relationship between abundance and dominant ground vegetation showed interesting patterns with time. While points with all the five categories of ground vegetation showed an increase in bird abundance as the season progressed, the degree to which it increased was starkly different in each. Points with Rubus sp. and those with Vaccinium sp. as the dominant ground vegetation were similar in terms of both average abundance and the increase in abundance with time; both were intermediate values. Points with graminoids in the ground layer had the lowest overall abundance as well as the lowest increase (Figure 3). Points with moss as the ground layer and those which had no dominant ground layer vegetation (category ‘Bare’) showed similar patterns—both had low abundances in the beginning but towards the end had the highest abundances. They showed the strongest increases in abundance. 

Figure 3: Abundance of all species of birds varying with habitat characteristics of each sampling point, as predicted by the best-fitting model ‘all.6’. (A) Coloured lines show mean abundances changing with weeks on X-axis. Coloured ribbons around the lines represent 95% CIs. (B) Large circular dots represent mean bird abundance per point count. Whiskers represent 95% CIs. Dark orange colour represents Week 1 and dark blue represents Week 13. (C, D) Coloured lines show mean abundances and corresponding ribbons represent 95% CIs. Dark orange colour represents Week 1 and dark blue represents Week 13.

## Habitat selection in forest bird guilds

The final models for invertebrate-feeders and omnivores were very different (see Table 3 for model selection steps). The former was a Poisson GLMM (log link) with observer, proportion of deciduous trees and dominant ground vegetation as important fixed effects, while there was no main effect or interaction term of week. Point was included as a random effect. Although the dominant ground vegetation was a useful predictor, the only deviant group was ‘Graminoids’; points which had graminoids as the dominant ground layer vegetation tended to have lower abundance of invertebrate-feeding birds than points with other ground layers (Figure 4). Abundance decreased with proportion of deciduous trees, and notably, a polynomial term did not give a better fit, although mixed forests with intermediate proportions of deciduous trees are believed to have higher diversity and abundance. Neither of the two trends changed detectably with time.

For omnivores, the final model was a negative binomial GLMM (log link) also containing just one random effect, of point. Observer, week, habitat class, tree density and canopy heterogeneity along with its interaction with week were all important and contributed to model parsimony. Omnivore abundance also increased as the season progressed, but overall abundance was higher in forest edges than in forest interiors or roadside patches (Figure 5). This trend did not interact with week. Omnivore abundance, similar to general bird abundance, decreased with tree density but showed interesting trends with canopy heterogeneity. At first, the trend appeared to be slightly negative yet almost insignificant, but with every week the trend became more and more positive, such that in week 13 it was very strong. Omnivores seemed to be highly abundant in points with the most heterogeneity, while abundances in points with the lowest heterogeneity remained the same as in week 1 (Figure 5). 


Table 3: GLMMs of guild abundances with habitat variables. Model names ‘inv.x’ refer to invertebrate-feeder models while names ‘omn.x’ refer to omnivore models. Models at each step of term addition/deletion are shown with their corresponding information such as degrees of freedom (df), predictor terms, log-likelihood, AICC (which was used as a selection criterion) and Akaike weight. ‘sTPD’: scaled proportion of deciduous trees; ‘DOM’: dominant ground vegetation; ‘HC’: habitat class; ‘CH’: canopy heterogeneity; ‘TD’: tree density.

Model	df	Predictors	logLik	AICc	Weight
inv.4	8	sTPD + DOM + observer + (1|point) 	-552.462	1,121.385	0.951
inv.3	6	sTPD + TR + observer + (1|point) + moss 	-557.916	1,128.098	0.033
inv.2	5	sTPD + observer + (1|point) + moss 	-559.998	1,130.186	0.012
inv.1	4	observer + (1|point) + moss	-562.141	1,132.408	0.004
omn.3	10	HC + log(CH) + log(TD) + week:log(CH) + observer + (1|point) + week	-880.043	1,780.678	0.981
omn.2	7	HC + observer + (1|point) + week	-887.149	1,788.597	0.019
omn.1	5	observer + (1|point) + week	-894.116	1,798.391	0.0001

Selected model, ‘inv.4’:
invertebrate-feeder abundance ~ observer + (1|point) + scaled proportion of deciduous trees + ground vegetation
Selected model, ‘omn.3’:
omnivore abundance ~ observer + (1|point) + week + habitat class + log(canopy heterogeneity) + log(tree density) + week:log(canopy heterogeneity)

 
Figure 4: Abundance of invertebrate-feeding birds varying with habitat characteristics of each sampling point, as predicted by the best-fitting model ‘inv.4’. (A) Large circular dots represent mean abundance per point count. Whiskers represent 95% CIs. (B) Line shows mean abundances and corresponding ribbon represents 95% CIs. X-axis shows proportions scaled from original range of 0–100%.
 
Figure 5: Abundance of omnivorous birds varying with habitat characteristics of each sampling point, as predicted by the best-fitting model ‘omn.3’. Dark orange colour represents Week 1, pink colour represents Week 7 and dark blue represents Week 13. (A) Large circular dots represent mean abundance per point count. Whiskers represent 95% confidence intervals. (B, C) Coloured lines show mean abundances and corresponding ribbons represent 95% CIs. 

## Post-breeding and pre-migratory behaviour of bird species

PCAs were done using data for the eight selected species in which abundances from the first three (PB) and last three weeks (PM) were summed in individual points. The measured habitat variables were fitted post-hoc using the envfit() function, so as to visualise how bird abundances were structured. 

There is a clear separation in the niches occupied by species in the two different guilds, and there are additional patterns within the guilds too. Among omnivores, the woodpeckers (‘Den_sp’ in Figure 6) seemed to have widely different preferences than other omnivores in both periods. In PB, the two tit species were closely linked while the nuthatch had slightly different preferences. But in PM, all three were close together which is line with the mixed foraging flocks that were sometimes seen (Figure 6). They also seemed to follow closely the proportion of deciduous trees.

With the exception of treecreepers, which seemed to be slightly separated from other species in both periods, all the invertebrate-feeders were clustered together in PB while they all diverged in terms of habitat preferences in PM. They were also following tree density and appeared to prefer forest interior to other habitat classes in PB, but they expanded their niches in PM presumably due to the shortage of invertebrate prey.
 
Figure 6: Ordination diagrams of PCAs done on bird data combined from (A) the first three weeks of the study (‘PB’); (B) the last three weeks of the study (‘PM’). Small circular dots represent the 32 sampling points and the colours represent habitat classes. Red denotes ‘Edge’, blue denotes ‘Interior’ and green denotes ‘Road’. Purple squares represent invertebrate-feeding bird species while yellow diamonds signify omnivorous species, and their corresponding labels are codes for their Latin names (see Table S2). Black arrows and corresponding labels (see Table S1) are the correlations of various habitat variables with the calculated PCA space, fitted using ‘envfit()’ function. Length of each arrow denotes correlation strength.

## Bird predation on plasticine caterpillars

The model (‘cat.2’) that best described the changes in bird predation rates across the study area and with the progress of the season was a GLMM with binomial error distribution (and logit link) having as fixed effects a second-order polynomial of week and a linear term of habitat class, and point as random effect (see Table 4 for model selection steps). 

Table 4: GLMMs of bird predation rates on plasticine caterpillars. Model ‘cat.0’ is the null model with Point and Week as linear fixed effects while ‘cat.1’ has a polynomial week term. Models at each step of term addition/deletion are shown with their corresponding information such as degrees of freedom (df), predictor terms, log-likelihood, AICC (which was used as a selection criterion) and Akaike weight. ‘UDi’: understorey diversity; ‘HC’: habitat class. 
Model	df	Predictors	logLik	AICc	Weight
cat.3	8	UDi + week + HC + week:UDi + (1|point) + poly(week,2) 	-281.454	579.511	0.843
cat.2	6	HC + (1|point) + poly(week,2) 	-285.264	582.877	0.157
cat.1	4	(1|point) + poly(week,2)	-296.566	601.297	0.00002
cat.0	3	(1|point) + week	-303.310	612.719	0.00000

Selected model ‘cat.2’
cbind(bird predations, non-predations) ~ (1 | point) + poly(week, 2) + habitat class


Nevertheless, the only habitat variable which was important in explaining the changes in caterpillar predation was habitat class. Predation was lowest in roadside points, and highest in forest edges and forest interior with the former appearing to have slightly higher rates. All-species bird abundance correlated poorly with predation rates (r = -0.0569, p = 0.3808) while the abundance of invertebrate-feeders suggested a slight negative correlation (r = -0.1395, p = 0.0518; marginally significant).

Since the predation study was conducted during only a subset of the whole study period, there are interesting gaps that could be worth looking further into. In week 5, predation rates were the highest and they decreased steadily in the following weeks. However, towards the end of the study, predation rates seemed to show a slight increase again, if not a complete reversal of the trend (Figure 7). Correlations of predation with bird abundances also show interesting albeit non-significant trends. The correlation with invertebrate-feeder abundances is marginally significant but negative, and perhaps could be picked up better with more data. The possible trend being negative is surprising as there seems to be no effect of the season at play (since the abundances of this guild did not show any relationship with week in the regression). 

Finally, it is worth mentioning one of the models (‘cat.3’) in the selection procedure that was not parsimonious enough but could possibly be suggesting a relationship. There was an interaction between understorey diversity and week that seemed to be legitimate but it did not substantially lower the AICC of the model (dAICC was 3.4 on 2 df). However, this is probably due to the data itself being insufficient and the effect is entirely plausible. At first, predation decreased with increasing understorey diversity but towards the end the trend was flattened and even slightly positive (not shown). No other habitat characteristics except understorey diversity could be considered as potentially affecting predation. 

Figure 7: (A, B) Predation rate on artificial caterpillars varying with time and habitat class of each sampling point respectively, as predicted by the best-fitting model ‘cat.2’. Coloured lines as well as coloured circles with black borders represent mean predation rates. Non-opaque dots are observed data points. Red colour denotes ‘Edge’, blue denotes ‘Interior’ and green denotes ‘Road’. Dark orange colour represents Week 5, pink colour represents Week 9 and dark blue represents Week 12. (C, D, E) Observed values of bird, invertebrate-feeder and omnivore abundances respectively in each sampling point and week plotted against observed values of predation rate from the same point and week. Note the absence of significant correlations. 

# Discussion

The general increase in bird abundance seen with the progress of the season could be due to migrants arriving from the north to winter here, such as multiple tit species, but could also be due to better detection rates as the birds become bolder and more active, especially with the formation of large (and sometimes mixed) foraging flocks.

One of the biggest difficulties in studying bird communities in the non-breeding season is believed to be their low detectability. While we observed this to be true—birds were relatively very quiet, inconspicuous and inactive, particularly in PB—we realised that it was not as low as expected. The very low number of instances of birds feeding on fruits was unexpected. This could have been because arthropod abundance in the forest was still high enough to support the birds, or it could mean that birds in this region (mostly non-migrants or partial migrants) do not show the popular shift in foraging strategy that is seen elsewhere, particularly in North America (see Parrish, 1997, 2000), and rather only feed on fruits facultatively. However, since arthropod abundances were not measured in the study, it is hard to make definitive arguments. 

The continuous measure of time (and seasonality) used in this study was considered to be better than comparing categorical factors like ‘post-breeding period’ and ‘pre-migratory period’, for a few reasons. Firstly, there is a fair degree of arbitrariness and ambiguity in published studies in this field regarding exact definitions of such seasons. Moreover, such categories might have very different meanings and implications depending on location. For instance, ‘pre-migratory periods’ in the northernmost parts of Scandinavia would be extremely different from those in, say, southern Czech Republic. This makes comparability difficult. Instead, measuring in numbers of weeks identified by a standard time unit (the Gregorian calendar) allows easy interpretability of results. And finally, such a measurement of time provides a much finer temporal resolution than would time categories, which could be important in spotting patterns developing at a relatively short time scale. 

## Habitat selection in forest birds

The overall abundance of forest birds after the breeding season seemed to be higher in forest patches where the canopy was highly heterogeneous and lower in forest patches with uniform canopy cover. There was also a negative trend with tree density despite the two habitat variables not being significantly correlated. Since a vast majority of bird detections were auditory and since such temperate forests with poor understorey layers do not limit auditory detections, the possibility of poorer detection rates with high tree density can be ruled out. 

Heterogeneity has been explored before, but not in the same sense as in my study. For example, Freemark and Merriam (1986) observed positive trends of bird richness and abundance with overall habitat (rather than canopy) heterogeneity but also with forest size. They measured heterogeneity as a combination of different features such as species compositions of tree, shrub and ground strata and the forest structure. Their design consisted of multiple forest sites of varying areas and, naturally, heterogeneity was generally higher in larger forests. Hence, the results from their study do not relate well to those of mine, which concerned multiple points of the same area but of different qualities located within the same tract of forest. 

One explanation for the trends then can be that both variables lead to higher light availability within the forest, which can be crucial for invertebrate-feeders particularly towards autumn when the conspicuous prey are all depleted. The trends did not interact with week, suggesting that these preferences are driven not by seasonally changing conditions (at least not at the scale I considered) but rather by some fundamental and more general driver. Canopy cover was not included in the models and hence its effect(s) cannot be compared. However, a potential reason that heterogeneity might be more important to birds than cover is that heterogeneous patches might provide better light conditions while still retaining at least some of the other desirable properties of the habitat. On the other hand, patches with very low average cover, despite having good light conditions, might not have sufficiently good vegetation characteristics. 

In spite of the significant correlations between canopy heterogeneity and canopy cover, and between canopy cover and tree density, canopy heterogeneity and tree density remained uncorrelated (see Figure S6). This could be indicating two separable properties of canopy cover that often go unnoticed when comparing species responses such as abundance, richness or diversity with only canopy cover. Moreover, although the correlation between canopy cover and tree density is statistically significant, it seems weak at low densities of trees. This could mean that the trends with bird abundances are influenced not just by the availability of light. While heterogeneity may be allowing for better light conditions, low tree densities might be related to some other feature of the patch that is favourable to birds. 

For example, Menon and Shahabuddin (2021) found that tree density across various sites in a low-latitude temperate forest, comprising both protected and managed patches, was highly negatively associated with mean tree girth, and observations suggested a negative relationship with canopy height as well. These could be due to suppressed regeneration and sapling growth caused by shade effects, and both variables were positively linked with bird abundance and richness (Menon and Shahabuddin, 2021). Although I did not measure canopy height and tree girth, the same trends can be expected here too. Wider trees can be expected to host a larger and more diverse group of arthropod prey species as a result of greater diversity of microhabitats, thereby favouring a higher abundance of birds. 

Mixed forests with intermediate proportions of deciduous trees are generally believed to have higher biodiversity (e.g., Jansson and Andrén, 2003; Hagar, 2007; Ohno and Ishida, 1997; Felton et al., 2010). Alatalo (1981) observed that bird density increased linearly with proportion of deciduous trees in the summer, while the relative use of such habitats declined in winter. If not a linear relationship, bird abundances are expected to show a hump-shaped trend, with highest values found in mixed forests and lowest in both purely coniferous and purely broadleaved patches. However, tree density, with which the proportion of deciduous trees was correlated in my study, explained the variability in bird abundances better—neither a linear term nor a polynomial of the scaled proportion provided better fits. 

Features of the understorey layer did not matter, even though the presence of shrubs in the understorey is generally expected to be good for small passerines. In my sampling points, the common species in the understorey were alder buckthorn and spruce, followed by pedunculate/sessile oak and birch. Other species occurred rarely and even when they did, were in very few numbers, sparse and isolated. This might explain the absence of a trend in bird abundance with understorey characteristics. These characteristics such as richness and diversity might not be captured with a wide enough range in my study area so as to matter for the birds. Hence, different patterns could be expected in other less-managed and naturally more diverse forests.

The dominant ground layer vegetation had a great effect on bird abundances, which was surprising because there is no reason to expect any special preference to one or the other species. However, these patterns could be merely reflecting some other feature that birds track. Rubus sp. and Vaccinium sp. ground layers were associated with similar and intermediate values of average bird abundance and increase in abundance, while moss and no-dominant (‘Bare’) ground layers were associated with similar values but had very low abundances in the beginning and very high values in the end. Graminoids like Carex spp. were associated with lowest average abundance as well as its increase. 

In general, canopy heterogeneity, understorey density and understorey diversity were not particularly different between the different groups of points. There were weak patterns of the dominant layer with some habitat features: all groups except ‘Rubus’ had similar values of canopy cover while ‘Rubus’ had a lower mean and larger overall range of values; ‘Graminoid’ had slightly lower richness and diversity of canopy trees than others. The strongest patterns were seen in terms of coniferous/deciduous trees and tree density. The ‘Moss’ points (two in total) had the highest tree densities, a very low proportion of deciduous trees and a very high number of spruce trees, relative to all other points (Figure S7; see also Figure S2 A). Some of the ‘Bare’ points (i.e., with no dominant ground layer vegetation) also had high tree density and high numbers of spruce, but others had varied characteristics. ‘Rubus’ had the lowest tree densities, high proportions of deciduous trees and low spruce numbers. Others had mostly intermediate values. The relation with pine was similar to that with spruce, although ‘Moss’ and ‘Rubus’ did not have as extreme values. Finally, ‘Moss’ points had the lowest numbers of oaks and ‘Graminoid’ points had the highest, while others had intermediate numbers. A special case worth mentioning is that of Larix decidua. It occurred prominently in only two points, but according to my system was always considered as deciduous (and not as coniferous). 

There seems to be a complex interplay of presence of conifers and density of trees. Several points other than ‘Bare’ and ‘Moss’, including one ‘Graminoid’ point, had relatively low proportions of deciduous trees but most of these were pine and not spruce. And, all other ‘Graminoid’ points had high numbers of oak. ‘Rubus’ and ‘Vaccinium’ points generally had mixed canopies as well as low tree densities. ‘Moss’ points had numerous spruces and very high tree densities. All this could be suggesting that in PB, birds preferred mixed forest patches that had some canopy heterogeneity and low densities of trees (which could in turn be related to tree girth, but also to proportion of deciduous trees). However, in PM, although such points still had relatively high abundances and hence can be considered as generally good for birds, an even greater increase in bird abundance was seen in points with highly dense canopy structure composed mainly of spruce. These spruce-dominated points were very poorly inhabited by birds in PB but had the highest abundances in PM. 

Thus, while mixed species composition, canopy heterogeneity and low tree density are the best features generally, spruce-dominated dense patches represent an initially low-value niche that turns into a high-value niche. Pine, the other common conifer, did not have any major effect and was not as important as spruce was. ‘Graminoid’ points which had high oak numbers and generally low canopy heterogeneity were poorest for birds in both periods. This is a surprising result, as oaks are usually linked with higher biodiversity (especially Q. robur, which is highly insect-rich and has the highest visitation rates by birds), but can perhaps be better understood at a deeper level of response, i.e., at the level of guilds.

Alatalo (1981) observed that in general, mixed forests had the highest bird densities while pure pine forests and forests with low trees had the lowest bird densities. However, he also noticed that in winter, foliage-gleaners preferred pine over spruce, presumably due to the abundance of eggs of Lachnidae on pine needles. However, this is the opposite of what I observed, although it was not exactly in winter. Alatalo (1981) also suggests that species like Regulus regulus and Turdus spp. forage in pine forests in late summer, despite avoiding it during the nesting season. Berg (1997) noticed that the ground vegetation was related to tree species composition—‘grass’ vegetation had large volume of deciduous trees, which is in agreement with my observations of ‘Graminoid’ points, and Vaccinium spp. had more pine, which is different from what I observed. However, Berg also observed positive correlations of bird abundance with spruce and none with pine (similar to my result), but this was during the breeding season, when spruce is believed to be preferred over pine due to its special canopy structure that provides protected nest sites. Nevertheless, he suggests the possibility of differences in productivity and food availability being important criteria as well.

The reason the overall trend with tree density in the model is negative could be that the degree of avoidance of high-density spruce patches in PB might have been relatively high, and the subsequent preference in PM might not have been high enough to appear as an interaction of the variable. It became visible, however, when points were split into groups. Secondly, tree density provides a better fit than proportion of deciduous trees despite their significant correlation, probably because of the variability in values; the same value of tree density can arise in both conifer-dominated and deciduous broadleaf-dominated patches (see Figure S6). The two variables could have different implications to the birds and hence could be selected for differently. 

## Habitat selection in forest bird guilds

The two guilds showing different patterns is indirect evidence of differences in their resource-use strategies. Further, while abundance of omnivores increased with time, that of invertebrate-feeders remained largely constant (as inferred from the lack of a notable effect of week in the model). This agrees with the fact that most of the northern migrants that arrive here are omnivores (mostly tits), and also suggests that detectability of the naturally quiet invertebrate-feeders was not a major issue in this study. If there actually was an increase in true abundance in PM, it would have to mean that detectability was higher in PB and lower in PM, which is highly unlikely.

Abundance of invertebrate-feeders decreased linearly with proportion of deciduous trees and was lower in graminoid-dominated points. Thus, they were clearly avoiding oak-dominated patches with low canopy heterogeneity, while their preferences were mostly similar among the other points regardless of whether they were spruce-dominated or mixed forest patches. However, tree density gave a poorer fit than proportion of deciduous trees, and this could be indicating the different implications of the two variables in spite of their correlation.

Invertebrate-feeders not preferring deciduous trees is surprising, given that oaks are generally considered to host good numbers of arthropod prey, but this could be because of a few different reasons. A majority of the herbivorous arthropods on oaks belong to Lepidoptera (45% of the total species richness of phytophages on Q. robur/petraea; Kennedy and Southwood, 1984), which attain a peak density in spring. The trees see relatively very low lepidopteran attacks after mid-June (Feeny, 1970). When considering all phytophagous insects, there is a second but much smaller peak in abundance in late summer and early autumn of suckers, leaf-miners and gall-formers (Southwood et al., 2004). Thus, the overwhelming preference for oaks by arthropods, and consequently by predatory birds, is likely to be prevalent mainly in spring and summer. The arthropod communities of oaks and their regulation by predators has rarely been explored in the post-breeding periods of late summer and early autumn.

Moreover, the specific invertebrate-feeding species present during this summer-autumn transition period such as treecreepers, robin and goldcrest/common firecrest are largely specialists and do not prey on external-feeding herbivores. Treecreepers are bark-feeders, robin is mostly a ground-forager and goldcrest is specialised for spruce (firecrest shows no preference for either conifers or broadleaf trees; Leisler and Thaler, 1982). In fact, even omnivores like the great tit have been shown to preferentially feed on conifers like pines (Eeva et al., 1997).

The model for omnivores had a negative binomial distribution, which is in concordance with the large foraging flocks seen among omnivore species such as tits. Abundance increased with time, likely due to the migrants, but average abundance was highest in forest edges. Abundance decreased with tree density like in the case of all birds, and there was no relationship with the dominant ground layer vegetation. Their preference of the structural feature (tree density) over the species’ biological characteristics like coniferous/deciduous suggests that being generalists, they are not particular about the food source. In the beginning, there was no major trend in abundance with canopy heterogeneity although the birds seemed to prefer less heterogeneous points. However, this was completely reversed by the end of the study, with the most heterogeneous points having the highest abundance—twice that of the least heterogeneous points which did not see any change in bird abundance at all over the course of the season. 

Although invertebrate-feeders did not show preference to or against heterogeneous patches, omnivores seemed to have avoided them in the early weeks, the reason for which is not obvious. The subsequent arrival of the migrants caused an occupation of the previously ‘empty’ niche and this was most likely because heterogeneity enables the formation of large foraging flocks, with different individuals in the party focussed on different aspects of the habitat. This, in combination with higher light availability, would result in higher foraging efficiency, which is crucial in the pre-migratory period. The fact that the dominant ground vegetation was not important to omnivore abundance especially with the arrival of the migrants further solidifies that structural features were the only things they tracked, and that they were otherwise rather evenly distributed over the study area.

Wolfe et al. (2014) suggested that because forest-dwelling arthropod species are often cryptic (Bond, 2007), it may be inherently difficult and inefficient for an insectivore to directly assess the availability of arthropods, particularly in resource-scarce periods. They suggested this to be the reason why frugivores and insectivores tracked different cues. However, in my study, the species belonging to the ‘invertebrate-feeder’ group are naturally specialised on cryptic prey species. This could be why they tracked the qualitative features of the food resources (even if not directly but by the coniferous/deciduous distinction) over structural characteristics. On the other hand, the generalist omnivores would have had difficulty foraging for these cryptic species, and hence attained higher foraging efficiency by tracking structural characteristics, especially with the formation of foraging flocks.

## Post-breeding and pre-migratory behaviour of bird species

The dissimilarity in niches occupied by the two guilds is evident in the ordinations too. Even among omnivores, the divergent Dendrocopos spp. might be showing a preference for deciduous trees, in that it occurred in points with intermediate proportions of deciduous trees and intermediate tree densities. Thus, for them, the biological trait of coniferous/deciduous was well-linked with the associated structural characteristic of density. While hole-nesting birds, such as woodpeckers, are known to prefer deciduous trees for breeding and for better predator protection, in my study this seemed to be also the case in both PB and PM. Despite being omnivorous, they occupied a different niche than the small omnivorous passerines like tits and nuthatch, which makes sense due to their vastly different foraging strategies. The nuthatch preferences were slightly different from those of tits in PB while they converged in PM, facilitating the mixed-species foraging flocks. 

On the other hand, with the exception of treecreepers, invertebrate-feeders showed a divergence in strategies in the PM. This was possibly due to the shortage of prey in this period, which would have increased competitive pressure, forcing them to diverge. This is most notable in the case of Regulus spp. and Phylloscopus spp. which are both foliage-gleaners, although the feature they tracked most was still tree density. Robin and treecreepers appeared to expand slightly into more deciduous patches in PM relative to PB. Interestingly, although the statistical models were unable to pick up any major trends with understorey features, the ordinations seem to suggest that there were indeed some, particularly for invertebrate-feeders and in PB. This further solidifies the possibility that other more ‘natural’ and less-manipulated forests with a much wider range of understorey features than seen in Branišovský les could show different patterns.

Overall, the bird communities defined by these eight species across the three habitat classes of my study points were more similar in PM, suggesting a relatively generalist strategy. In PB, the communities of the three habitat classes were more separated than in PM, when they overlapped greatly.

## Bird predation on plasticine caterpillars 

In general, not many studies have looked at changes in predation rates with season (but see e.g., Molleman et al., 2016 in the tropics). There are two main assumptions that can be made in interpreting the results from my study. First, predation rates on the dummy caterpillars can be assumed to be associated with the true predation rates (i.e., predation on actual arthropod prey) prevalent at that particular time. Or second, the plasticine predation rates can be assumed to not reflect accurately true predation rates. The method of studying predation rates using artificial caterpillars fails to accurately match the natural predation rates and are usually conservative (Howe et al., 2009), although not many have studied this question in the summer-autumn transition in temperate regions. Nevertheless, the use of model prey permits a standardised, rapid assessment of relative predation rates across the seasonal gradient and between different points. 

Thus, the plasticine predation only approximates true predation. However, there are two further assumptions that can be made. This link (under- or overestimated approximation) can be assumed to be with either the general arthropod predation rates, or specifically lepidopteran predation rates. The latter appears to be most reasonable, as the artificial caterpillars used in the study were made to resemble generic lepidopteran larvae of oaks in Central Europe. Moreover, there was no evident shift towards frugivory (as inferred from the very low fruit foraging observations relative to overall foraging observations [2/494 = 0.4%]) despite the decline in predation. So, the former assumption can be discarded. 

It is then safe to assume that birds are able to distinguish, to some extent, between artificial and natural caterpillars. Additionally, simply by virtue of probabilities, predation on artificial prey correlates negatively with availability of natural prey (data of Volf et al., 2021). Thus, an increase can be expected in predation on artificial prey with a significant decline in natural prey availability. In my study, bird predation on artificial caterpillars declined considerably over the weeks and was affected to a much lesser extent by habitat class. Other habitat variables did not have a detectable impact in my study area. This decline could be either because natural prey availability increased, or because birds lost interest in the artificial prey over the course of the season in spite of an unchanged natural prey availability.

In my study, arthropod abundances were not monitored. Arthropod availability has been shown by a few studies to be consistent across seasons (e.g., Moorman et al., 2007, but 2012 found lower densities only in spring migration) but this is dependent on location and the temporal stability of the respective conditions, even among temperate forests. More importantly, arthropod abundances in the same forest as in my study have been shown to peak in late spring (May and early June) but later stabilise at low levels (Kollross et al., unpubl.). Hence, the possible explanation of the decline in predation on artificial caterpillars by a complementary increase in natural prey availability can be ruled out.

Other experiments using artificial caterpillars with breeding birds have found that they represent a new and attractive resource for the birds, which often try to find the largest, most profitable prey for their nestlings (Díaz et al., 1998; Naef‐Daenzer et al., 2000; Hino, 2002) regardless of nutritional quality (Brodmann and Reyer, 1999). Mäntylä et al. (2008) found that predation increased initially in their experiment, then decreased as birds learned that the artificial prey offer no nutritional reward. However, their study was conducted during the breeding season when birds are territorial and therefore the same local birds can be expected to come into contact with the artificial caterpillars multiple times, resulting in the ‘learning’. In another case, predation on artificial prey in the breeding season directly decreased as the birds quickly learned the exact locations (Mrazova and Sam, 2018). On the other hand, in my study conducted in the non-breeding season, with young naïve birds and high mobility, it is unlikely that the same bird encountered the same artificial caterpillars multiple times. Moreover, unlike in Mäntylä et al. (2008), there was no initial increase observed in predation rates, but there was a slight increase towards the end. Thus, there might be other causes for the loss of interest in artificial prey (and consequent decline in predation rates) with the progress of the season.

Although several researchers have reported that lepidopterans are an important food resource (Robinson and Holmes, 1982; Wheelwright, 1986; McMartin et al., 2002; Yard et al., 2004), Moorman et al. (2007) observed that lepidopterans were important for ground-gleaning birds in PB but were otherwise less valuable than coleopterans and hymenopterans. In foliage-gleaning birds, lepidopterans were always less preferred, leading to the absence of an observable relationship (Moorman et al., 2012). They found that the relationship between foliage-gleaning bird abundance and foliage-dwelling arthropods was positive in ‘post-breeding’ but negative in ‘fall migration’. However, some patterns might be artifacts, and there is a general lack of studies linking prey abundance and predation rates with progressing seasons. As external-feeding lepidopterans are probably not a very important food source for the specialist invertebrate-feeding species in my study, most of the attacks on the artificial caterpillars (that resemble external-feeding lepidopterans) can be assumed to have been by omnivores. 

This could then mean that the model caterpillars represented a low-value but easy-to-find food source. Their (attempted) use might have been relatively high in the early weeks when the birds were not very active and mobile, whereas later on they might have been able to exploit better resources that were earlier difficult and inefficient to find. This explains the trend I observed. For example, the large foraging flocks might have aided foraging and allowed birds to expand in terms of their preferences, with different members of the flock focussing on slightly different prey. The slight suggestion of a reversal of the trend towards week 12 of the study could then have been due to depletion of these high-value arthropod prey items, especially if lepidopterans are not the preferred resource. This could have forced them to revert to the previous suboptimal strategy.

The study period from week 5 to week 12, due to the delay of one month in starting the experiment, captures only a short part of the ‘post-breeding’ season of Moorman et al., and a major portion of their ‘fall migration’. Since the abundance of arthropods can be assumed to not have changed greatly over the season, then under the assumption of a negative relationship between foliage-gleaning bird abundance and foliage-dwelling arthropods (Moorman et al., 2012), the seemingly (yet non-significant) negative correlation between predation rates and bird abundances would translate to a positive trend between predation rate and true arthropod abundance. However, this stands on too many assumptions, especially considering that arthropod abundance was not monitored and that the correlation was statistically non-significant. Therefore, it is difficult to make definitive conclusions about the decline in lepidopteran predation without complementary data on arthropod availability throughout the same period.

Nevertheless, my data showed that predation rates in general were highest in forest edges and interior, and lowest in roadside habitats. The similarity in rates between forest edges and forest interior is interesting. Some studies (e.g., Rodewald and Brittingham, 2004; Marshall et al., 2003; Bowen et al., 2007) have suggested higher arthropod abundances in gaps or edges compared to mature forest as the cause of higher bird abundances, while some have shown birds to be tracking vegetation structure in gaps rather than arthropod abundances (e.g., Moorman et al., 2012). However, the patterns observed in my study (similar predation rates in forest edges and interior) might also be due to the long history of management in the forest, whereby heterogeneity in the conventional sense usually attributed to edge habitats might no longer be very relevant to the birds that are mobile and easily cross small interruptions (Lord and Norton, 1990). Although low-traffic forest roads have been shown to attract birds by increasing heterogeneity relative to the interior of commercial forests (Šálek et al., 2010), the poor predation rates seen in my roadside points could be because the forest interior is not extremely homogeneous (due to patches of varying levels of manipulation). It could also be because the roads considered here see high traffic. Still, these points were slightly better in terms of bird abundance, so this question remains unanswered.

My results are partially in agreement and partially discordant with those of Leles et al. (2017), who found that fragmentation effects were not important and diversity, species composition and structural features of the plant community importantly affected predation rates. However, their study was done in a tropical system and a large majority of the predation was due to ants. Since my study found no detectable effect of vegetation characteristics on predation by birds, this could mean that the tropics and temperate regions have different top-down control dynamics. Or, it could be because my study area did not have enough variation in vegetation characteristics, and hence the same study repeated in a different forest could give different results. Nevertheless, forest edges and interior had similar rates of predation in my study, which is in partial agreement with their findings.

There are clearly some patterns in food resource use of birds with season, but pinpointing the exact mechanisms would require a much more focussed and larger dataset. An example of this data being insufficient is provided by the suggestion of a relationship between understorey diversity and week in explaining predation rates. Many studies (e.g., Blake and Hoppes, 1986; Martin and Karr, 1986) have observed arthropod and bird abundances to be related to understorey vegetation. In my study, predation seemed to increase with understorey diversity initially, but towards the end showed a flat trend. Nevertheless, this suggestion was not strong enough to form conclusions from. 

## Summary and implications

The general increase in bird abundance as the season progressed was likely not due to better detection rates but rather because of the arrival of migrants from the north, although trapping and tracking of individual birds is necessary to be absolutely certain of this. There was no visible shift of foraging strategy to frugivory, despite several such results elsewhere, particularly in North America. At the level of all bird species, there were important effects of canopy heterogeneity and tree density on bird abundance, which were not linked with seasonality but rather indicated a general preference. Although several studies consider habitat heterogeneity, not many look at canopy heterogeneity, which, from this study, appears to be important. The general effects of canopy cover can be separated into those of heterogeneity—which might affect birds through light conditions—and those of absolute densities—which might indirectly affect or might be linked with other aspects of the habitat such as tree girth. 

Further, birds in my study generally did not care about features of the understorey. However, this could be a pattern specific to Branišovský les, and similar studies in other temperate forests of Central Europe are required and encouraged. Birds overall cared more about habitat structure (tree density) than about indirect resource qualities (proportion of deciduous trees) despite their strong correlation. They did show selectivity in terms of the dominant ground layer vegetation, but this was most likely linked to other attributes. Patches with mixed canopy composition (broadleaved and coniferous trees), heterogeneous canopy and low density of trees always have good abundances of birds. Highly dense spruce-dominated patches are initially very poor for birds, but later become very good possibly due to prey availability. Patches with homogeneous canopies dominated by oak represented the worst habitat for birds in both periods, but this particular pattern is driven by the invertebrate-feeding guild. 

The guild-level models, ordinations and predation results all suggest that even though arthropods seemed to be the major food source for both guilds, the strategies of resource use were slightly different among the two. Abundance of invertebrate-feeders did not change markedly with time, while that of omnivores did. Omnivores had to adjust and accommodate the new arrivals. Invertebrate-feeders were selective only about avoiding homogeneous oak-dominated patches, and were otherwise broad in resource-use. Oak-dominated patches might not provide the appropriate groups of prey for these specialist birds. While this could be an inference generalisable to the overall non-breeding season, when oaks do not have a disproportionately better arthropod pool, it is also possible that other forests with different species compositions in the invertebrate-feeding guild (with less specialists) might show different patterns. Omnivores, on the other hand, did not seem to be specific about food resources directly, but rather showed structural preferences for forest edges with low tree density and high canopy heterogeneity. The latter was extremely important in accommodating the northern arrivals and presumably also enabled the large mixed-species foraging flocks. In PM, passerine omnivores shared resource use strategies while invertebrate-feeders were divergent. 

Bird predation on artificial caterpillars showed a major decline but also seemed to increase slightly towards the end of the study. The decline could be indicating a shift in feeding preferences of birds with time. Lepidopterans may not be the ideal resource, and as mobility and foraging efficiency increase, particularly as they form flocks, birds are able to forage for higher-quality prey such as coleopterans and hymenopterans. However, these resources might be getting depleted towards week 12, thereby forcing birds back to feed on lepidopterans (and model caterpillars resembling lepidopterans). The decline could also be due to the birds learning that the models do not have nutritional quality. Points in the forest interior and in edges had similar predation rates. This could be a pattern applicable to other forests with a long history of management and commercial manipulation. Roadside points were poorest for bird predation. Further conclusions are impossible to make, but this highlights the scarcity and importance of studies looking at seasonal variation in predation rate and arthropod abundance.

## Caveats and improvements

The bird count data had a considerably high observer effect. Although it was statistically accounted for in all the models by inclusion as a fixed effect, it is not easy to predict how exactly it might have affected the observed results. Further similar studies should aim for a study design that does not involve multiple observers (or involves a large number of observers), or if absolutely necessary, should establish more rigorous protocols to avoid biases as much as possible, such as with distance estimation.

The measure of canopy heterogeneity used in this study, although interesting, can be improved. Perhaps five sub-points within the point (or more depending on the radius under consideration), rather than three, can be used so as to get a more accurate measure. Canopy height, stratification and age of forest are variables that could have important effects on the kind of question asked in this study and hence can be incorporated. Multiple studies (e.g., Goetz et al., 2007; Hinsley et al., 2009) have found vertical stratification features of the canopy detected by lidar to be better predictors of bird species richness across multiple habitat types than traditional measures of canopy cover.

Conducting similar studies in different, and possibly larger, forest tracts will be crucial in understanding the generality of these observed patterns and in determining the level of plasticity and adaptability that bird species are capable of. Sampling points should be chosen so as to obtain equal numbers in each category of predictors such as habitat class and dominant ground vegetation. Additionally, having continuous data starting from the pre-breeding period will be extremely useful, as it can serve as a reference but can also potentially show larger patterns. Similarly, the changes in predation rates should also be explored for a much longer period of time, and should incorporate measures of arthropod abundance (in addition to bird abundance) to provide a complete picture. However, the arthropod surveys must be exhaustive and should consider not just the external-feeding herbivores but also other groups of arthropod prey.

# Conclusion

Habitat selection is a fundamental part of the ecology of organisms. Selection of habitats by birds is affected by various factors including reproduction, competition, food availability, etc. In the non-breeding season in temperate areas, the major concern is expected to be food availability, due to the approaching autumn and, eventually, the winter. Things are not made easier by the arrival of migrants from the north, resulting in a higher overall resource consumption. Studying habitat selection during this period can provide useful information about the various strategies employed by different species and the interactions between them.

There was a general increase in bird abundance caused by the arrival of northern migrants. In addition, I found varying degrees of habitat selection at different levels. Overall bird abundance was driven by a combination of structural characteristics and species composition of the vegetation. However, the two guilds showed different resource use strategies. Invertebrate-feeding birds only cared about one major characteristic, but were highly specific and consistent about it: they avoided oak-dominated homogeneous patches of forest and preferred spruce patches with heterogeneity. On the other hand, omnivores were affected by a larger interplay of factors and their patterns changed with time (with the arrival of migrants): they had a slight preference for forest edges with low densities of trees and this remained constant with time, but they formed an additional strong preference for highly heterogeneous areas as the season progressed. While there is no evidence to show that birds stopped feeding on arthropods, there was a marked decline in predation rates on the artificial caterpillars, which can be assumed to imperfectly mirror patterns of decline in predation of true lepidopteran prey. However, the trend seemed to be rising back up towards the end of the study, which provides a very interesting point for further inquiry.

Thus, the poorly-studied topic of habitat selection in post-breeding temperate forest birds and their corresponding foraging strategies is a very promising avenue to lead future research down. It can lead to valuable insights on the interactions of these birds with their natural environment during stressful periods, and can possibly suggest recommendations on the right action to take in order to make and maintain these heavily managed and exploited habitats suitable to them.

# Bibliography

